<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-T0N1AST" ignored="0" name="Login Test" tests="3" failures="1" timestamp="09 Oct 2019 01:38:02 GMT" time="29.052" errors="0">
  <testcase name="doLogin" time="18.062" classname="testcases.LoginTest">
    <failure type="java.lang.AssertionError" message="Got actual result as Login_Success">
      <![CDATA[java.lang.AssertionError: Got actual result as Login_Success
at com.qtpselenium.keywords.GenericKeywords.reportFailure(GenericKeywords.java:111)
at com.qtpselenium.keywords.AppKeywords.validateLogin(AppKeywords.java:39)
at com.qtpselenium.driver.DriverScript.executeKeywords(DriverScript.java:52)
at testcases.LoginTest.doLogin(LoginTest.java:50)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- doLogin -->
  <testcase name="doLogin" time="0.004" classname="testcases.LoginTest">
    <skipped/>
  </testcase> <!-- doLogin -->
  <testcase name="doLogin" time="0.003" classname="testcases.LoginTest">
    <skipped/>
  </testcase> <!-- doLogin -->
</testsuite> <!-- Login Test -->
